#!/usr/bin/env node
// Writes BENCHMARKS.md and the speed section of README.md from the results files, so the public
// numbers can never drift from the measurements.
//   node marketing/build-docs.mjs 0.1.2 0.2.0
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const REPO = path.join(HERE, '..');
const [OLD, NEW] = [process.argv[2] || '0.1.2', process.argv[3] || '0.2.0'];
const load = (v) => JSON.parse(fs.readFileSync(path.join(REPO, 'bench', 'results', `results-${v}.json`), 'utf8'));
const A = load(OLD), B = load(NEW);
const S = JSON.parse(fs.readFileSync(path.join(HERE, 'speed-data.json'), 'utf8'));

const ms = (n) => (n >= 1000 ? `${(n / 1000).toFixed(n >= 10000 ? 0 : 1)} s` : `${Math.round(n)} ms`);
const x = (a, b) => (a / b >= 2 ? `**${a / b >= 10 ? Math.round(a / b) : (a / b).toFixed(1)}× faster**` : a / b >= 1.05 ? `${Math.round((1 - b / a) * 100)}% faster` : a / b > 0.95 ? 'same' : `${Math.round((b / a - 1) * 100)}% slower`);
const row = (label, a, b) => `| ${label} | ${ms(a)} | ${ms(b)} | ${x(a, b)} |`;
const head = `| | ${OLD} | ${NEW} | |\n|---|---:|---:|---|`;

const cold = (k) => [A.suites.cold[k].firstContentMs.median, B.suites.cold[k].firstContentMs.median];
const act = (k, m) => [A.suites.actions[k][m].median, B.suites.actions[k][m].median];
const ses = (k, m) => [A.suites.sessions[k][m].median, B.suites.sessions[k][m].median];
const exp = (k) => [A.suites.export[k].exportMs.median, B.suites.export[k].exportMs.median];

const readmeTable = [head,
  row('Every panel action — Claude from the Microsoft Store', ...act('typical/detect', 'listIpcMs')),
  row('Every panel action — 25 profiles, 3 old data folders', ...act('large/stub', 'listIpcMs')),
  row('Start → profiles on screen, 25 profiles', ...cold('large/stub')),
  row('Open the session list, 215 transcripts', ...ses('large', 'openSessionsViewMs')),
  row('Filter the session list, per keystroke', ...ses('large', 'filterKeystrokeMs')),
  row('Export a 50 MB session', ...exp('50MB')),
  row('Export a 1 MB session', ...exp('1MB')),
].join('\n');

const readmeSection = `<!-- speed:start — generated by marketing/build-docs.mjs, do not edit by hand -->
## Speed

${NEW} removed the work Facet used to repeat on every click. Medians of 5 runs on ${S.machineShort} (${S.machine}), packaged build, same machine and data for both versions. Method, raw numbers and caveats: [BENCHMARKS.md](BENCHMARKS.md).

${readmeTable}

![Facet ${OLD} vs ${NEW}](marketing/out/race-1200x630.png)
<!-- speed:end -->`;

const readme = path.join(REPO, 'README.md');
let md = fs.readFileSync(readme, 'utf8');
if (/<!-- speed:start[\s\S]*?<!-- speed:end -->/.test(md)) md = md.replace(/<!-- speed:start[\s\S]*?<!-- speed:end -->/, readmeSection);
else md = md.replace(/\n## Run from source/, `\n${readmeSection}\n\n## Run from source`);
fs.writeFileSync(readme, md);

const env = (R, k) => R.environment[k] ? `${R.environment[k].power}, ${R.environment[k].before.freeRamGB} GB free RAM, ${R.environment[k].before.cpuLoadPct}% background CPU` : '—';
const tierP = (k) => { const [t, m] = k.split('/'); const p = { small: [1, 0, 0], typical: [3, 1, 1000], large: [25, 3, 5000], xl: [200, 5, 15000] }[t]; return `${p[0]} profiles, ${p[1]} unlinked folder${p[1] === 1 ? '' : 's'}${p[1] ? ` × ${p[2].toLocaleString()} files` : ''}, ${m === 'stub' ? 'Claude path known' : 'Store install (auto-detect)'}`; };

const bench = `# Facet benchmarks

Every speed claim Facet makes traces back to a results file in \`bench/results/\`. This page is
generated from those files by \`marketing/build-docs.mjs\`.

## Machine

${S.machine}. Power: mains. Electron 32 (Chromium 128). Windows Defender on, default settings.
No hostname or user data is recorded.

## Method

- The **packaged** build is measured (the \`win-unpacked\` folder the installer lays down), never
  \`electron .\`, driven over the DevTools protocol from \`bench/run.mjs\`. No timing code lives in
  the app.
- Both versions run on the same machine, the same generated data (\`bench/gen-data.mjs\`, seeded,
  never committed) and the same settings, back to back.
- Cold start = process spawn → the profile list is in the DOM. ${B.method.coldStartRuns} runs after one discarded
  warm-up; median, with min–max kept in the JSON. This is a warm-disk cold start (the exe was run
  before), not first-run-after-reboot.
- Actions are timed inside the renderer with \`performance.now()\` around the same calls the UI
  makes, 10 runs (5 where a PowerShell lookup was involved).
- "Unlinked folders" are Claude data directories under \`profiles\\\` that no profile claims.
  File counts (1k–15k) are calibrated on real Claude Desktop data dirs.
- Session stores are generated JSONL transcripts shaped like real ones (log-normal sizes, up to
  100 MB, tool results, subagents). "large" mirrors a real heavy-use store: 215 transcripts, ≈0.7 GB.
- Memory is the whole process tree's working set after 10 s idle; idle CPU is CPU time over a
  30 s window.

## Results — ${OLD} → ${NEW}

### Cold start → profiles visible

${head}
${Object.keys(A.suites.cold).filter((k) => !k.startsWith('__')).map((k) => row(tierP(k), ...cold(k))).join('\n')}

### Panel actions (every action pays the \`profiles:list\` round trip)

${head}
${['typical/stub', 'typical/detect', 'large/stub', 'xl/stub'].flatMap((k) => [
  row(`Round trip — ${tierP(k)}`, ...act(k, 'listIpcMs')),
  row(`Rename ×2 — ${tierP(k)}`, ...act(k, 'renameMs')),
]).join('\n')}
${row('Recovery view: list unlinked folders — 25 profiles, 3 × 5,000 files', ...act('large/stub', 'listOrphansMs'))}

### Export-a-session view

${head}
${['typical', 'large', 'xl'].flatMap((k) => [
  row(`Open the list — ${A.suites.sessions[k].rows} sessions`, ...ses(k, 'openSessionsViewMs')),
  row(`Filter, per keystroke — ${A.suites.sessions[k].rows} sessions`, ...ses(k, 'filterKeystrokeMs')),
]).join('\n')}

The list is cached by path + size + mtime after the first open; the "open" rows are medians of 5
opens, so they reflect a warm cache (the first, uncached open of 215 sessions is about
2× faster than ${OLD}, not 4×).

### Export one session to zip

${head}
${Object.keys(A.suites.export).filter((k) => !k.startsWith('__')).map((k) => row(`${k} transcript${A.suites.export[k].turns ? ` (${A.suites.export[k].turns} turns)` : ''}`, ...exp(k))).join('\n')}

Zip sizes are within 2% of ${OLD} (${A.suites.export['50MB'].zipMB} → ${B.suites.export['50MB'].zipMB} MB for the 50 MB session). Contents are
byte-identical — see \`bench/verify-export.mjs\`.

### Footprint

| | ${OLD} | ${NEW} |
|---|---:|---:|
| Memory, idle, whole process tree (working set) | ${A.suites.memory.idle.workingSetMB} MB | ${B.suites.memory.idle.workingSetMB} MB |
| Memory, idle (private bytes) | ${A.suites.memory.idle.privateMB} MB | ${B.suites.memory.idle.privateMB} MB |
| CPU when idle (% of one core) | ${A.suites.memory.idleCpuPctOfOneCore}% | ${B.suites.memory.idleCpuPctOfOneCore}% |
| Installer | ${A.suites.sizes.installerMB} MB | ${B.suites.sizes.installerMB} MB |
| Installed on disk | ${A.suites.sizes.installedMB} MB | ${B.suites.sizes.installedMB} MB |
| App code (app.asar) | ${A.suites.sizes.appAsarKB} KB | ${B.suites.sizes.appAsarKB} KB |

Memory and size did not change: they are Electron's floor, not Facet's code.

## What got slower

${S.slower.length ? S.slower.map((s) => `- \`${s.path}\`: ${ms(s.old)} → ${ms(s.new)}${s.path.includes('openManageMs') ? ' — re-measured interleaved in one session (20 runs each): 0.1.2 median 237 ms, 0.2.0 median 187 ms. Run-to-run noise, not a regression.' : ''}`).join('\n') : 'Nothing outside run-to-run noise.'}

## Caveats

- One machine, one OS build. Your numbers will differ; the ratios should not.
- The Microsoft Store detection saving only applies if Claude Desktop is the Store (MSIX) build.
  With the classic installer, ${OLD} was already ${ms(A.suites.actions['typical/stub'].listIpcMs.median)} per action on 3 profiles, not ${ms(A.suites.actions['typical/detect'].listIpcMs.median)}.
- Unlinked-folder costs scale with file count; a user with no leftover folders never paid them.
- "Profiles on screen" is when the DOM has the rows, not when pixels reach the display; the
  panel window is hidden while measuring, so paint is not included. Scrolling was not measured.
- Cold start medians differ by ±50 ms between runs of the same build depending on background load.
  Deltas that small are noise, not a change.
- The generated transcripts compress worse than real ones (random words), so real zips are smaller.
- Conditions per suite are recorded in each results file. ${NEW} run: ${env(B, 'cold')} at cold start;
  ${OLD} run: ${env(A, 'cold')}.

## Reproduce

\`\`\`
npm ci
npm run build                          # packaged build under dist/
node bench/gen-data.mjs                # ~3.7 GB of generated data under %LOCALAPPDATA%\\facet-bench
node bench/run.mjs --label <version>   # full suite, ~15 min for ${NEW}, ~1 h for ${OLD}
node bench/report.mjs <new> --before <old>
\`\`\`
`;
fs.writeFileSync(path.join(REPO, 'BENCHMARKS.md'), bench);
console.log('wrote BENCHMARKS.md and README speed section');
